# Generated by Django 2.0.13 on 2021-07-05 16:21

from django.db import migrations, models
import django.db.models.deletion
import pkpromo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abiturientus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=256, verbose_name='ФИО')),
                ('code', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Абитуриент',
                'verbose_name_plural': 'Абитуриенты',
            },
        ),
        migrations.CreateModel(
            name='AbiturientusFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pkpromo.models.generate_filename)),
                ('file_type', models.CharField(choices=[('pd', 'Заявление о согласии на обработку ПД'), ('zayava', 'Заявление'), ('passport', 'Паспорт'), ('docobrazov', 'Документ об образовании'), ('snils', 'СНИЛС'), ('other', 'Иные документы')], max_length=256)),
                ('abiturientus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pkpromo.Abiturientus')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=69, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
