# Generated by Django 2.2.1 on 2021-07-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkpromo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abiturientus',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='abiturientus',
            name='status',
            field=models.CharField(blank=True, choices=[('decline', 'Отклонено'), ('accept', 'Согласовано'), ('seen', 'Просмотрено')], max_length=30, null=True, verbose_name='Статус'),
        ),
    ]
