# Generated by Django 2.2.1 on 2021-07-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkpromo', '0002_auto_20210707_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiturientus',
            name='status',
            field=models.CharField(choices=[('default', 'не установлен'), ('decline', 'Отклонено'), ('accept', 'Согласовано'), ('seen', 'Просмотрено')], default='default', max_length=30, verbose_name='Статус'),
        ),
    ]
