# Generated by Django 2.2.1 on 2022-06-22 09:38

from django.db import migrations, models
import pkpromo.models


class Migration(migrations.Migration):

    dependencies = [
        ('pkpromo', '0003_auto_20210707_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiturientusfile',
            name='file',
            field=models.FileField(max_length=256, upload_to=pkpromo.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='abiturientusfile',
            name='file_type',
            field=models.CharField(choices=[('pd', 'Заявление о согласии на обработку ПД'), ('zayava', 'Заявление'), ('zachisl', 'Заявление о согласии на зачисление'), ('passport', 'Паспорт'), ('docobrazov', 'Документ об образовании'), ('snils', 'СНИЛС'), ('other', 'Иные документы')], max_length=256),
        ),
    ]
